FROM rust:1.74 as builder

WORKDIR /app

COPY Cargo.toml Cargo.lock /app/
COPY src /app/src/

ENV CARGO_BUILD_TARGET x86_64-unknown-linux-musl
ENV CARGO_BUILD_TARGET_DIR /tmp/target

RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release

FROM scratch

COPY --from=builder /tmp/target/x86_64-unknown-linux-musl/release/snowlhive /usr/local/bin/snowlhive

ENTRYPOINT ["/usr/local/bin/snowlhive"]
